### ISSUE TITLE
Switch dialog to whiptail ?

### ISSUE THREAD

**Issue by kilbith** [joukewitteveen/netctl#134]
`whiptail` is more universal, discard much better the standard streams, and does not re-create a dialog box in the terminal whenever the program is called (i.e. no need to `clear` your screen).

The downside is that `whiptail` is less feature complete than `dialog`, but that would suffice for `wifi-menu`.

- http://linux.die.net/man/1/whiptail
- https://en.wikibooks.org/wiki/Bash_Shell_Scripting/Whiptail

**Comment by joukewitteveen** [comment]
Is there any issue with dialog you run into? As far as I can tell `whiptail` is not more 'universal' than `dialog`, it is just installed by default on Debian, which makes it rather popular. `dialog` introduces no dependencies besides what `bash` already has. Hence `dialog` is as lightweight and portable as we can get. Am I missing something?

We could turn all invocations of `dialog` into `$DIALOG`, which defaults to `dialog` but could be set to `whiptail`, say. We would check whether `dialog` is installed only when  `$DIALOG` is not set, which could lead to unexpected behavior when `$DIALOG` is set to a command that is not installed. Also, we do not benefit from any possible benefits of either of the tools as we are then restricted to the lowest common denominator of their functionality.

**Comment by kilbith** [comment]
`NetworkManager` [requires](https://www.archlinux.org/packages/community/x86_64/libnewt/) `whiptail` via `libnewt`. Nowadays pretty much every distro ship `NetworkManager`. Arch does not ship `dialog` by default, and you can also note it is bigger than the `newt` library itself...

As from a technical standpoint, as I said `whiptail` doesn't flood your terminal with new dialog boxes every time e.g. you press an entry. The cursor block is hidden and you don't have to worry much of the manifestation of `stderr` / `stdout` / `stdin` — it is correctly handled, while `dialog` can "freeze" during a streaming and scrolls your dialog box to the top.

Please give it at least a try.

**Comment by joukewitteveen** [comment]
Why would you want `NetworkManager` if you have `netctl` ;-)? `libnewt` depends on `s-lang` which makes a `libnewt` installation approximately 10 times as large as a `dialog` installation. Either way these figures are hardly relevant given the price of storage. Portability is relevant though. Note that in Arch Linux `dialog` sits in the `Core` repository, whereas `libnewt` sits in `Community`.

I took a quick look at `whiptail` to see how difficult it would be to implement my idea of abstracting over the dialog program. Since `whiptail` outputs strings on `stderr` it is not straightforward to assign the output of `whiptail` to a variable. Sure, it can be done, but not in a way that would be transparent to the `$DIALOG` abstraction unless we use `stderr` for dialog too, which I don't consider very beautiful.

If you come up with some impressive patch I might reconsider, but I am not going to put any more effort in this. I like the current `ncurses` interface and cannot distill any true bugs from your report.

**Comment by kilbith** [comment]
> Since whiptail outputs strings on `stderr` it is not straightforward to assign the output of whiptail to a variable

Did you try something like this : 

```Bash
REPLY=$(whiptail ... 3>&2 2>&1 1>&3)
```

I also notice you need to `clear` your screen 5 times in your current code with `dialog`. You would not have to with `whiptail`. I might prepare a patch for fallbacking to `whiptail` if `dialog` ain't installed, with your agreement.

**Comment by joukewitteveen** [comment]
Yes, I am aware of that technique and that is precisely what I meant by 'not straightforward'. In your snippet you forgot to close fd 3, which shows just how easy it is to get these things wrong.
You could prepare a patch, but I don't give it a high a priori probability of getting accepted. I don't see a bug in the usage of `clear` and I don't see anything wrong with using `ncurses` either.
