### ISSUE TITLE
dmenu compatibilty

### ISSUE THREAD

**Issue by LordTaifleh** [joukewitteveen/netctl#145]
Hi there, i want to fork wifi-menu to be compatible with dmenu and similar programs. 
Can you give me a detailed view of exactly what data i need to feed wifi-menus subroutines that depend on user IO and what dialog returns exactly, so i get them to work? 
I am trying to figure it out by myself, but after spending the last two days unsuccesfully on that, i feel slightly discouraged.
Any help would be appreciated.

`init_entries()` returns a "string"array, as far as i can see. it contains ( _ = space, \t = tab )
```
'_--_WLAN1_'*: wep\t  :-64
'_--_WLANX_'+:wpa2\t  :-55'
'_--_WIFIY_'_:none\t:  -53'
```
^ the most difficult part for me is figuring out the exact formatting which is output to dialog, because i need to work with it without breaking the rest

**Comment by joukewitteveen** [comment]
Hi! Thanks for picking netctl as a project to hack on.
`init_entries()` fills up the `$ENTRIES` array. This array is set up so that it can be [passed as an argument to `dialog --menu`](https://github.com/joukewitteveen/netctl/blob/a8f6fb14484702ffb3ff60847546419c27830dd1/src/wifi-menu#L269). This means that the elements come in tag/item pairs, where the item contains tab-separated fields.
