### ISSUE TITLE
what is ForceConnect?

### ISSUE THREAD

**Issue by overdetermined** [joukewitteveen/netctl#154]
From the manual:

'ForceConnect='::
    Set to `++yes++' to force connecting even if the interface is up.
Do not use this unless you know what you are doing.

Instead of "you know what you are doing." perhaps one could provide a slightly better description in another sentence or something.
"All other networks may be ignored." Or whatever (other) ramifications this may have.

(This is just a hint from someone who is trying to get into the habit of reading manuals more carefully. This is great software and I appreciate any effort that goes into improving it! Since I have no idea what ForceConnect is and whether it will solve my problem at hand i opened this ticket, please excuse the frank wording.)

**Comment by joukewitteveen** [comment]
Thanks for taking the time to help make `netctl` better! The phrase 'unless you know what you are doing' is one that I remember from the days where I configured my own kernel builds. I like it as a form of deterrent and therefore chose to use it in the `netctl` manual as well.

Really, I have not yet come across any use case for `ForceConnect=`. Every use of it 'in the wild' is an indication of a miss-configured (or at least badly behaving) system. When set to `yes`, a simple check to see whether the network interface is not yet configured is _skipped_. Without it, `netctl` is pedantic and refuses to touch an interface that is (attempted to be) brought up by the user or, more commonly, other network managers. By design, `netctl` will not attempt to guess the users intentions and will only work when it is allowed to be 'in charge of the network interface'.

If you can think of a better wording of the man page, let me know. Also, if you are now convinced that 'unless you know what you are doing' is scary enough without wasting a lot of words on it, let me know too :-).

**Comment by kovetskiy** [comment]
@joukewitteveen when I install fresh Arch Linux, my network interface is already up, so I use `ForceConnect` directive in every profile on my every machine. 

Maybe I do something wrong with my systems, but I didn't have any network settings at all. Just install netctl, wifi-menu, dialog packages and connect to wifi.

**Comment by joukewitteveen** [comment]
@kovetskiy well, _something_ is bringing your interface(s) up! It would be interesting to find out what is responsible for that. Have you checked that you are not also using any of the dhcp services (e.g. dhcpcd.service) or another network manager (including systemd's `networkctl`)?

**Comment by overdetermined** [comment]
Haha, lot's of people with nothing to do on a sunday? 

@joukewitteveen thanks for the fast and detailed response. I personally believe the phrase "know what you are doing" is perfect and in this case hints at the point that I should tread carefully. Interestingly enough I'm also an arch-linux user who is wondering why my wifi-connection is "patchy" on two of my systems. Unfortunately, I don't track my steps very adamantly so I can't tell your everything I have done, but maybe there is something wrong with the default installation of arch, since my second system is a fresh install from last week and to the best of my knowledge have only been using netctl and wifi-menu.

If I find out what is wrong, I'll let you know and most probably close this issue.

**Comment by kovetskiy** [comment]
@joukewitteveen what kind of problem you are solving by disallowing connecting to wifi in case when interface is already up? What the problems can appear if netctl became more tolerant to status of interface?

**Comment by joukewitteveen** [comment]
Problems become very hard to debug when software tries to be smart. When started, `netctl` simply takes an interface and configures it according to its profile. When it is stopped (or fails to configure the interface as specified), `netctl` rolls back all configuration and brings the interface back down. Nice and predictable.

Configuring an interface that is already up hides configuration problems (multiple network managers) and means that your system is configured differently after a `netctl stop` than it was before `netctl start`.

**Comment by overdetermined** [comment]
OK, so after some reading, the only thing I would change is 

'ForceConnect='::
Set to `++yes++' to force connecting even if the interface is up/configured.
Do not use this unless you know what you are doing.

may or maynot be pedantic but I've mulled over what my problem could be and still no luck. I randomly get spikes in ping which essentially reset themselves (before an upgrade (6-12 months ago) they did not and I had to reset manually). I do have dhcpcd service started but I'm pretty sure that is required for my LAN connection since I have only enabled netctl service for my wireless connection. What I might try is write small program that detects the spikes so that I can debug more easily. OK I'm rambling. Thanks for the help @joukewitteveen.

**Comment by joukewitteveen** [comment]
Hmm, interesting suggestion. Thanks for that. However, since the true use of the variable is
https://github.com/joukewitteveen/netctl/blob/1.14/src/lib/network#L41-L45
I think we should not suggest that we check on the interface being 'configured' in any way. Hence I will leave it at this (at least for now) and congratulate you on now knowing pretty well what you are doing with regard to that variable ;-).

I assume the dhcpcd service is started for a specific interface other than the one under `netctl`s control? If not, that may be a first step towards a solution.

If anyone can find out why a fresh install of Arch Linux apparently has its interface brought up, than that would be good to know. It is probably a bug (or questionable feature) in the Arch installation scripts.

**Comment by overdetermined** [comment]
Hi again,
I'm still having this problem. I'm using arch-linux so i should be fairly up to date what the releases are. I have no idea whether things changed with netctl or other programs i'm running.

However, when I experience a network outtage, I found that opening wifi-menu, connecting to a random network and then reconnecting to mine alleviates the issue. Fairly recently I have been getting the following message upon first opening wifi-menu:

Interface 'wlp0s29u1u6' is controlled by netctl-auto

wlp0s29u1u6 is my personal wifinetwork.

I'm not sure what the root cause is, but i've been suspecting using google services (gmail, and search) correlates with the cause. So much so that i've stopped using google as the default search engine. I feel like a paranoid nutcase, but this is the state of affairs. If I have more info I will let you know.

**Comment by kovetskiy** [comment]
I have a problem ForceConnect too, actually, I can't use any new wifi after reboot until I add "ForceConnect=yes" to the netctl profile, because I use dhcpcd service (enabled in systemd). I need it for wired networks. I tried to enable dhcpcd only for wired interfaces but then I noticed that my wireless interface doesn't acquire any IP when connected to wifi. (should netctl-auto run his own dhcpcd instance?).

Is there any global netctl configuration? I would like to set "ForceConnect=yes" for all profiles once in the time.

**Comment by joukewitteveen** [comment]
Sorry for the delay in responding.
Please, do not use the issue tracker as a forum for help. I would love to solve everyone's gripes, but simply do not have the time to do so. To reach a large base of knowledgeable users, I suggest turning to the [Arch Linux forums](https://bbs.archlinux.org/).

@overdetermined: It is highly unlikely that using google services has anything to do with connection problems. I suspect that you have multiple networking services enabled, possibly multiple netctl services. Using `netctl-auto@<interface>.service` simultaneously with either `netctl@<profile-using-the-same-interface>.service` or `netctl.service` is not expected to work.

@kovetskiy: hooks can be used for global configuration. From `man netctl.profile`:

    Whenever a profile is read, all executable scripts in /etc/netctl/hooks/
    and any executable script in /etc/netctl/interfaces/ with the name of the
    interface for the profile are sourced. Declarations in an interface
    script override declarations in a profile, which override declarations in
    hooks.
