### ISSUE TITLE
Add route and gateway in specific route table

### ISSUE THREAD

**Issue by amosbird** [joukewitteveen/netctl#157]
Hi, can we have this route table specific feature added in netctl ? Thanks!

**Comment by joukewitteveen** [comment]
Can you make this proposal more specific? What do you want to achieve and how do you think this should work?

**Comment by amosbird** [comment]
I'd like to have this configuration work.

```
Routes=('192.168.0.0/24 via 192.168.1.2 table foo')
Gateway='172.24.10.1 table bar'
```

**Comment by joukewitteveen** [comment]
I reckon the routes part already works. In fact, I guess this would do what you want:
```
Routes=(
    '192.168.0.0/24 via 192.168.1.2 table foo'
    'default via 172.24.10.1 table bar'
  )
```
So the question is, do we want table support for `Gateway=` and if so, how do we implement it. The problem is that the Gateway variable sort of assumes that there is a unique gateway in your profile, but with routing tables this assumption does not hold. Moreover, the `table bar` part is `iproute2`-specific syntax, which I'd rather avoid. So we could invent new syntax or introduce more variables, but is any of that worth it?

Can you test the above suggested configuration? If it works the best idea may be to just document it.

**Comment by amosbird** [comment]
Ah, it works fine. Thanks!
