### ISSUE TITLE
netctl wanted by multi-user.target, slowing down boot

### ISSUE THREAD

**Issue by aeubanks** [joukewitteveen/netctl#174]
The slowest part of my boot sequence is waiting for netctl to either succeed or fail. It seems that's because netctl adds itself to `/etc/systemd/system/multi-user.target.wants` during a `netctl enable some-profile`.

I'm not sure that `multi-user.target` should wait for netctl to succeed (or fail), does it make sense to decouple the two? And just have systemd start up netctl separately.

**Comment by joukewitteveen** [comment]
netctl follows systemd target logic, and by default has these relations to several targets:

Services for profiles are tied in with **multi-user.target** so that they are activated with multi-user mode. Note though, that services for profiles start up near instantaneous. In particular, they do not wait for a profile to come 'online'.

In order to allow for preliminary interface configuration, netctl services are ordered after **network-pre.target**.

There is a vague notion of 'configured-but-not-necessarily-online' that is represented by **network.target**. This target is only reached after netctl services are activated. Recall that netctl services start up quickly.

A slightly less vague notion is that of being 'online', which roughly means that we can and no how to route traffic over an interface. This state is reached when **network-online.target** is reached. By default, netctl does not do anything with this target, since not all profiles are necessarily critical for a connection that is considered 'functioning'.

Now comes the interesting part. You can tell systemd to only consider **network-online.target** to be reached after services for netctl profiles are fully online by enabling `netctl-wait-online.service`. This includes all profiles that are enabled, which might not be what you want. Therefore, you can also set `WaitOnline=yes` per profile. This, however, has the effect that startup of the profile takes until it is fully online.

As for why you experience delays with netctl, there are a few reasons why services for profiles may be slow to start up. The most obvious one is that you have `WaitOnline=yes` in your profile. Alternatively, it could be that you use WPA and the WPA station is not configured properly, causing some form of timeout. However, none of these reasons should hold up your boot sequence, unless you have ordered important parts of it after **network-online.target** or **network.target**. This is usually not desirable, precisely because it makes booting slow (as is to be expected and entirely intentional).

**Comment by aeubanks** [comment]
I haven't enabled `netctl-wait-online.service` and nothing has `WaitOnline=yes`. This affects both my laptop using Wifi and my desktop using Ethernet so I don't believe this is related to WPA.

`network-online.target` doesn't seem to be involved here, I think it's `network.target`.

The following is what I based this issue off of:
```
$ systemd-analyze critical-chain
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

graphical.target @8.660s
└─multi-user.target @8.655s
  └─getty.target @8.648s
    └─getty@tty1.service @8.641s
      └─systemd-user-sessions.service @8.617s +14ms
        └─network.target @8.609s
          └─netctl@wlp2s0\x2dfoo.service @2.683s +5.924s
            └─sys-subsystem-net-devices-wlp2s0.device @2.681s
```

This seems to be the issue
```
$ sudo netctl enable wlp2s0-foo

'/etc/systemd/system/multi-user.target.wants/netctl@wlp2s0\x2dfoo.service' -> '/usr/lib/systemd/system/netctl@.service'
generated '/etc/systemd/system/netctl@wlp2s0\x2dfoo.service.d/profile.conf'
```

```
$ cat /usr/lib/systemd/system/netctl@.service
[Unit]
Description=Networking for netctl profile %I
Documentation=man:netctl.profile(5)
After=network-pre.target
Before=network.target netctl.service
Wants=network.target

[Service]
Type=notify
NotifyAccess=exec
RemainAfterExit=yes
ExecStart=/usr/lib/netctl/network start %I
ExecStop=/usr/lib/netctl/network stop %I
```

It looks like `netctl@.service` has `Before=network.target netctl.service`, which I think is why it's on the critical chain. I believe this makes `network.target` wait for `netctl@.service` before proceeding.

Experimenting...
```
$ systemctl disable netctl@
Removed /etc/systemd/system/multi-user.target.wants/netctl@wlp2s0\x2dfoo.service.
```
This removes it from the critical chain, but then after a reboot I can't login to a graphical session unless I manually `netctl start wlp2s0-foo`.

**Comment by joukewitteveen** [comment]
Indeed, 5.924s seems very long! Here is what I did to profile `netctl` on my own machine.
I added `NETCTL_DEBUG=yes` to my profile and modified `/usr/lib/netctl/globals` by changing the debugging function to:
```
report_debug() {
    is_yes "${NETCTL_DEBUG:-no}" && echo "DEBUG ($SECONDS): $*" >&2
}
```
This is what ended up in my journal:
```
Oct 05 09:58:37 Mindship-03 network[428]: Starting network profile 'my_profile'...
Oct 05 09:58:37 Mindship-03 network[428]: DEBUG (0): wpa_start: wpa_supplicant -q -B -P /run/wpa_supplicant-wlan0.pid -i wlan0 -D nl80211,wext -c/run/netctl/wpa_supplicant-wlan0.>
Oct 05 09:58:38 Mindship-03 network[428]: DEBUG (1): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:38 Mindship-03 network[428]: DEBUG (1): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:39 Mindship-03 network[428]: DEBUG (1): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:39 Mindship-03 network[428]: DEBUG (2): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:39 Mindship-03 network[428]: DEBUG (2): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:39 Mindship-03 network[428]: DEBUG (2): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:39 Mindship-03 network[428]: DEBUG (2): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 kernel: wlan0: authenticated
Oct 05 09:58:40 Mindship-03 kernel: wlan0: associated
Oct 05 09:58:40 Mindship-03 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): wpa_call: wpa_cli -i wlan0 -p /run/wpa_supplicant status
Oct 05 09:58:40 Mindship-03 network[428]: DEBUG (3): network_ready: systemd-notify --ready
Oct 05 09:58:40 Mindship-03 systemd[1]: Started My Profile.
Oct 05 09:58:40 Mindship-03 systemd[1]: Reached target Network.
Oct 05 09:58:40 Mindship-03 systemd[1]: Starting Permit User Sessions...
```

I note now that I did not need to add timestamping to netctl, as the journal already has timestamps. Anyway, `systemd-analyze blame` tells me that `netctl` took 3.777s and the journal tells me that this was spent waiting for the wpa_supplicant. I think this is the way it should be.

Maybe you can add `NETCTL_DEBUG=yes` to your profile and find out what causes your delay? Please let me know!

**Comment by aeubanks** [comment]
Sorry for the delay.
A while back I tried to figure out exactly how to debug following your instructions, but couldn't get it to work.

Recently I just switched to NetworkManager and the critical path no longer contains any networking stuff (and overall it feels faster booting up), so I'm happy enough with the setup. The total boot time was 3.4s instead of the ~8s above.
