### ISSUE TITLE
Check config file when restart command

### ISSUE THREAD

**Issue by ardadmira** [joukewitteveen/netctl#183]
Why did not checks config file when `netctl restart _interface_` command ?

**Comment by joukewitteveen** [comment]
Can you be a bit more precise? You cannot restart an _inerface_ through `netctl`, only a _profile_. When you do so, you effectively do `systemctl restart netctl@PROFILE.service`. What more would you want from that command?

Or are you talking about `netctl-auto`?

**Comment by ardadmira** [comment]
I edited interface file and first time restart comamnd successful. I edited twice times this time config file syntax error and network is down. I'm talked already by `netctl restart` _interface_ command.

**Comment by joukewitteveen** [comment]
Ah, I think I see what you want. If I understand correctly, your idea is to run `bash -n PROFILE` before `netctl` `start`, `restart`, `switch-to`, `enable`. If that command determines that there is a syntax error, warn about it and don't proceed. That's a good idea, could you propose a patch?

**Comment by joukewitteveen** [comment]
I've posted a patch on https://lists.archlinux.org/pipermail/arch-projects/2021-January/005413.html
Unfortunately, it is not straight-forward to verify a profile file automatically before a restart, since the restart may be initiated by a user that does not have read access to the profile file. Use `netctl verify PROFILE && netctl restart PROFILE` to be safe.

**Comment by joukewitteveen** [comment]
Fixed in 9b70046f86b948c7e8c3c307f218c378714692ed, which will be part of the next release.
