### ISSUE TITLE
Use wifi-menu for connecting to hidden network

### ISSUE THREAD

**Issue by moneytoo** [joukewitteveen/netctl#89]
I think that it would be beneficial to allow connecting to hidden networks using wifi-menu (since wifi-menu is the first tool recommended according to Beginners guide on ArchWiki). 
IMHO it would take adding one more dialog for asking for ESSID (when the selected is empty), setting correct Hidden parameter to profile and also indexing list of networks by AP MAC (+ESSID) instead of current ESSID.
Any plans or would be such PR welcomed?

**Comment by Al-Caveman** [comment]
It will be much easier than editing the file, because wifi-menu offers a GUI menu. This is the reason we use wifi-menu: we do not want to know format of config files, we want intuitive GUIs, so we don't read manuals.

If editing a file is not a problem for us, we would not even use wifi-menu, and instead edit config files 100% of the time.

If you add hidden wifi to wifi-menu,, it will be a needed addition.
